<?php
/*********************************\ 
  DO NOT EDIT THIS FILE, PLEASE USE
  THE SETTINGS EDITOR
\*********************************/

$settings['load'] = "0";
$settings['mail_message_id'] = "0";
$settings['mail_parameters'] = "";
$settings['adminemail'] = "no-reply@red.piratenpartei.at";
$settings['extraadmininfo'] = "0";
$settings['allowaway'] = "0";
$settings['allowbuddyonly'] = "0";
$settings['allowcustomwarnings'] = "1";
$settings['pmsallowhtml'] = "0";
$settings['sightml'] = "0";
$settings['multirep'] = "0";
$settings['pmsallowmycode'] = "1";
$settings['sigmycode'] = "1";
$settings['negrep'] = "0";
$settings['neurep'] = "0";
$settings['posrep'] = "0";
$settings['postrep'] = "1";
$settings['pmsallowsmilies'] = "1";
$settings['sigsmilies'] = "1";
$settings['pmsallowimgcode'] = "1";
$settings['sigimgcode'] = "0";
$settings['pmsallowvideocode'] = "1";
$settings['allowmultipleemails'] = "0";
$settings['username_method'] = "2";
$settings['subscribeexcerpt'] = "100";
$settings['announcementlimit'] = "2";
$settings['attachthumbh'] = "96";
$settings['attachthumbw'] = "96";
$settings['readparentforums'] = "0";
$settings['avatardir'] = "images/avatars";
$settings['avatarresizing'] = "auto";
$settings['avataruploadpath'] = "./uploads/avatars";
$settings['boardclosed'] = "0";
$settings['boardclosed_reason'] = "These forums are currently closed for maintenance. Please check back later.";
$settings['bbname'] = "Sync-Forum Piratenpartei Österreichs";
$settings['bburl'] = "https://forum.piratenpartei.at";
$settings['captchaimage'] = "2";
$settings['coppa'] = "disabled";
$settings['canviewownwarning'] = "1";
$settings['unreadPostsStatusActionUnread'] = "1";
$settings['bbcodeinserter'] = "1";
$settings['smilieinserter'] = "1";
$settings['faxno'] = "";
$settings['contactlink'] = "mailto:forum@piratenpartei.at";
$settings['cplanguage'] = "english";
$settings['cpstyle'] = "default";
$settings['cookiedomain'] = "forum.piratenpartei.at";
$settings['cookiepath'] = "/";
$settings['cookieprefix'] = "";
$settings['customtitlemaxlength'] = "40";
$settings['wolcutoffmins'] = "15";
$settings['dateformat'] = "d.m.Y";
$settings['dstcorrection'] = "0";
$settings['dayspruneregistered'] = "90";
$settings['dayspruneunactivated'] = "90";
$settings['decpoint'] = ",";
$settings['bblanguage'] = "deutsch_du";
$settings['default_memberlist_sortby'] = "regdate";
$settings['default_memberlist_order'] = "ascending";
$settings['timezoneoffset'] = "+1";
$settings['delayedthreadviews'] = "0";
$settings['no_plugins'] = "0";
$settings['disableregs'] = "0";
$settings['tpr_selfrate'] = "1";
$settings['hiddencaptchaimage'] = "1";
$settings['failedlogintext'] = "1";
$settings['edittimelimit'] = "60";
$settings['enablecalendar'] = "1";
$settings['enableforumjump'] = "0";
$settings['enablememberlist'] = "1";
$settings['enablepms'] = "1";
$settings['enablereputation'] = "0";
$settings['tapatalk_chrome_notifier'] = "1";
$settings['tapatalk_push'] = "1";
$settings['enablewarningsystem'] = "0";
$settings['use_xmlhttprequest'] = "1";
$settings['tpr_closerate'] = "1";
$settings['seourls_archive'] = "1";
$settings['seourls'] = "yes";
$settings['tpr_undorate'] = "1";
$settings['enablepruning'] = "1";
$settings['tapatalk_enable'] = "1";
$settings['errorloglocation'] = "./error.log";
$settings['errorlogmedium'] = "log";
$settings['errortypemedium'] = "both";
$settings['unreadPostsExceptions'] = "61";
$settings['portal_announcementsfid'] = "2";
$settings['tpr_forums'] = "0";
$settings['modlist'] = "1";
$settings['redirects'] = "0";
$settings['gziplevel'] = "9";
$settings['searchhardlimit'] = "1000";
$settings['hiddencaptchaimagefield'] = "email3";
$settings['unreadPostsStatusCounterHide'] = "0";
$settings['tapatalk_hide_forum'] = "";
$settings['hideprivateforums'] = "0";
$settings['gomobile_homelink'] = "http://piratenpartei.at";
$settings['gomobile_homename'] = "Piratenpartei Österreichs";
$settings['homename'] = "Piratenpartei Österreichs";
$settings['homeurl'] = "http://piratenpartei.at";
$settings['tapatalk_datakeep'] = "keep";
$settings['siglength'] = "500";
$settings['logip'] = "no";
$settings['loginattemptstimeout'] = "15";
$settings['mail_logging'] = "0";
$settings['mail_handler'] = "mail";
$settings['mailingaddress'] = "";
$settings['maxloginattempts'] = "5";
$settings['avatarsize'] = "10";
$settings['maxattachments'] = "1";
$settings['maxavatardims'] = "80x80";
$settings['postmaxavatarsize'] = "60x60";
$settings['memberlistmaxavatarsize'] = "70x70";
$settings['maxpostimages'] = "10";
$settings['maxmessagelength'] = "16777215";
$settings['maxquotedepth'] = "5";
$settings['maxsigimages'] = "2";
$settings['maxpolloptions'] = "0";
$settings['maxmultipagelinks'] = "5";
$settings['maxpasswordlength'] = "300";
$settings['polloptionlimit'] = "0";
$settings['maxposts'] = "0";
$settings['maxregsbetweentime'] = "50";
$settings['maxreplength'] = "1";
$settings['maxnamelength'] = "30";
$settings['maxpostvideos'] = "1";
$settings['maxwarningpoints'] = "10";
$settings['membersperpage'] = "20";
$settings['postmergefignore'] = "";
$settings['postmergesep'] = "[hr]";
$settings['postmergeuignore'] = "4";
$settings['minmessagelength'] = "1";
$settings['minpasswordlength'] = "6";
$settings['minsearchword'] = "0";
$settings['minnamelength'] = "3";
$settings['gomobile_mobile_name'] = "Sync-Forum Piratenpartei Österreichs";
$settings['sigcountmycode'] = "0";
$settings['smilieinsertercols'] = "4";
$settings['smilieinsertertot'] = "20";
$settings['wordwrap'] = "80";
$settings['portal_numannouncements'] = "10";
$settings['failedcaptchalogincount'] = "5";
$settings['portal_showdiscussionsnum'] = "10";
$settings['failedlogincount'] = "10";
$settings['showbirthdayspostlimit'] = "0";
$settings['tplhtmlcomments'] = "0";
$settings['postfloodcheck'] = "0";
$settings['postfloodsecs'] = "60";
$settings['postlayout'] = "classic";
$settings['postmergemins'] = "0";
$settings['prunepostcount'] = "0";
$settings['postsperpage'] = "200000";
$settings['reCAPTCHA_PrivateKey'] = "";
$settings['pmfloodsecs'] = "0";
$settings['prunethreads'] = "0";
$settings['pruneunactived'] = "1";
$settings['enableprunebyposts'] = "1";
$settings['reCAPTCHA_PublicKey'] = "";
$settings['threadreadcut'] = "30";
$settings['refreshwol'] = "1";
$settings['tapatalk_reg_url'] = "member.php?action=register";
$settings['regdateformat'] = "M Y";
$settings['regtype'] = "verify";
$settings['hottopic'] = "20";
$settings['reportmethod'] = "db";
$settings['repsperpage'] = "15";
$settings['requirecomplexpasswords'] = "0";
$settings['returnemail'] = "";
$settings['secure_smtp'] = "2";
$settings['smtp_host'] = "localhost";
$settings['smtp_pass'] = "c04kHEtXS27EP8XDs4dUp-8bJltKjd";
$settings['smtp_port'] = "25";
$settings['smtp_user'] = "eNTi";
$settings['ip_forwarded_check'] = "0";
$settings['searchfloodtime'] = "10";
$settings['searchtype'] = "standard";
$settings['nocacheheaders'] = "0";
$settings['unreadPostsMarkAllReadLink'] = "1";
$settings['showsimilarthreads'] = "0";
$settings['showeditedbyadmin'] = "1";
$settings['showeditedby'] = "1";
$settings['attachthumbnails'] = "yes";
$settings['showdescriptions'] = "1";
$settings['showforumpagesbreadcrumb'] = "1";
$settings['showlanguageselect'] = "0";
$settings['portal_showdiscussions'] = "1";
$settings['multiquote'] = "1";
$settings['quickreply'] = "0";
$settings['portal_showsearch'] = "1";
$settings['showindexstats'] = "1";
$settings['subforumsstatusicons'] = "1";
$settings['threadreview'] = "1";
$settings['showbirthdays'] = "0";
$settings['showvernum'] = "0";
$settings['portal_showwol'] = "0";
$settings['showwol'] = "1";
$settings['portal_showstats'] = "1";
$settings['portal_showwelcome'] = "1";
$settings['portal_showpms'] = "1";
$settings['showforumviewing'] = "0";
$settings['similarlimit'] = "10";
$settings['similarityrating'] = "1";
$settings['statslimit'] = "15";
$settings['reCAPTCHA_Style'] = "red";
$settings['subforumsindex'] = "2";
$settings['unreadPostsCounterPages'] = "index.php";
$settings['tapatalk_directory'] = "mobiquo";
$settings['gomobile_theme_id'] = "11";
$settings['thousandssep'] = ".";
$settings['threadsperpage'] = "50";
$settings['betweenregstime'] = "2";
$settings['timeformat'] = "H:i";
$settings['failedlogintime'] = "15";
$settings['unreadPostsStatusCounter'] = "1";
$settings['unreadPostsStatusPostbitMark'] = "1";
$settings['unreadPostsMarkerStyle'] = "color:red;
font-weight:bold;";
$settings['uploadspath'] = "./uploads";
$settings['dotfolders'] = "1";
$settings['useerrorhandling'] = "1";
$settings['gzipoutput'] = "1";
$settings['usereferrals'] = "0";
$settings['allowthreadratings'] = "0";
$settings['gomobile_permstoggle'] = "0";
$settings['threadusenetstyle'] = "1";
$settings['gomobile_strings'] = "iPhone
iPod
mobile
Android
Opera Mini
BlackBerry
IEMobile
Windows Phone
HTC
Nokia
Netfront
SmartPhone
Symbian
SonyEricsson
AvantGo
DoCoMo
Pre/
UP.Browser
Playstation Vita";
$settings['userpppoptions'] = "";
$settings['usertppoptions'] = "10,20,25,30,40,50";
$settings['tpr_usergroups'] = "3,4,6,9";
$settings['browsingthisforum'] = "0";
$settings['browsingthisthread'] = "0";
$settings['emailkeep'] = "0";
$settings['hottopicviews'] = "150";
$settings['captchaprivatekey'] = "6LexbtYSAAAAALSRxjCz_Dx9TYkpd89jS9o2-aOm";
$settings['captchapublickey'] = "6LexbtYSAAAAACqRLQC4FKJsHSU7PDhWG80Vxkzw";

?>
